### ISSUE TITLE
The prices and hazard levels don't show up

### ISSUE THREAD

**Issue by TinyDerp** [AboveFire/ShowMoonPriceLLL#1]
I have no clue what's causing this because I have like 130 mods installed.
But I can tell you that only 6 of them are interacting with LLL and 3 of them are moons. No other mods are interacting with the moon page in the terminal.
![image](https://github.com/AboveFire/ShowMoonPriceLLL/assets/83468889/1e4e7dbf-ab4e-4604-b223-54ac7f53f45d)

**Comment by AboveFire** [comment]
I just uploaded an update to work with the new LLL version. It should be available soon in thunderstore

**Comment by TinyDerp** [comment]
Thanks!
Things seem to broken rn because of the new update, not only your mod.
