### ISSUE TITLE
WeatherTweaks's [UNKNOWN] weather breaks displaying prices

### ISSUE THREAD

**Issue by AndreyMrovol** [AboveFire/ShowMoonPriceLLL#2]
Hey, there's an incompatibility between my mod, [WeatherTweaks](https://thunderstore.io/c/lethal-company/p/mrov/WeatherTweaks/) and yours. 

As one of its features, it adds the possibility of having unknown weather condition (represented by `[UNKNOWN]` weather string in terminal), which breaks your mod's formatting.

![image](https://github.com/AboveFire/ShowMoonPriceLLL/assets/32998721/13493c7a-46a5-4f89-8001-eb0c720bc85d)

As you can see, when the weather is `[UNKNOWN]`, price and difficulty don't show up.

I've poked in your source code and pinned down the issue to this function: https://github.com/AboveFire/ShowMoonPriceLLL/blob/09c92214efe43b8782725a31971dfc9d6160434e/ShowMoonPriceLLL/Terminal_Patch_Override.cs#L85

It expects the weather to be between `(` normal brackets `)` (understandably), which my mod overrides causing the conflict.

Would you consider fixing this?

**Comment by AboveFire** [comment]
I could fix this yes. I'll see if I can do something more generic for this

**Comment by AboveFire** [comment]
Should be fixed with the new version that I just pushed to Thunderstore
