### ISSUE TITLE
Compatibility with Brutal Company Minus

### ISSUE THREAD

**Issue by TinyDerp** [AboveFire/ShowMoonPriceLLL#3]
The prices get all wonky when paired with [Brutal Company Minus](https://thunderstore.io/c/lethal-company/p/DrinkableWater/Brutal_Company_Minus/).
It doesn't break per say but it gets really hard to read. There used to be an option to turn off the terminal changes in Brutal Company Minus but it got removed a few updates back.

**Comment by AboveFire** [comment]
I see, I'll take a look and check what I can do about this compatibility.

**Comment by TinyDerp** [comment]
Thanks for taking a look into it. I'll close this then.
